### ISSUE TITLE
Blank page testing authentication

### ISSUE THREAD

**Issue by vmdef** [otatarintseva/samlidp#1]
Hello.

After following installation and configuration instructions, when I was testing moodle-userpass from the web interface (module.php/core/authenticate.php) I got a blank page.

After removing state param from getUser function (modules/moodle/lib/Auth/Source/External.php) I got it working smoothly. It is invoked without params in function authenticate (same file). Can you check if it was a local fault in my environment or it should be fixed?

**Comment by otatarintseva** [comment]
The issue was fixed.
